kind: pipeline
type: docker
name: default

steps:
- name: test
  image: owncloudci/nodejs:14
  commands:
  - npm install
  - npm test

trigger:
  ref: 
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**
